<a href="https://colab.research.google.com/github/rubisco99/DSCI_100_Grp_Project_Summer/blob/main/Stat301_project_Syryll_Ofiana.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#STAT 301 Group Project

The purpose of this R Notebook is to compile all the code, perform data analysis, and render summary statistics needed for the written report in [Overleaf](https://www.overleaf.com/4922554254crwjrcpkfkmw#4b6dbb). The Overleaf version will be the finalized version that will be submitted on

###Due date: **August 2, 2026**.


leranjamesw@gmail.com

syryllofiana@gmail.com

ezraheayie@gmail.com

xuethan2004@gmail.com


Main form of communication: Instagram

In [14]:
# Install the packages
install.packages("RSQLite")
install.packages("DBI")

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

In [15]:
library(DBI)
library(RSQLite)
library(reticulate)
library(dplyr)
library(ggplot2)
library(knitr)

# Install kagglehub if needed and import python modules
system("pip install kagglehub")

py_run_string("
import kagglehub

# download database
path = kagglehub.dataset_download('wyattowalsh/basketball')
print('Downloaded to:', path)
")

# path to sqlite file from python
dataset_dir <- py$path
db_path <- file.path(dataset_dir, "nba.sqlite")

# connect to database
con <- dbConnect(RSQLite::SQLite(), db_path)

# check tables
tables <- dbListTables(con)
print(tables)

 [1] "common_player_info"  "draft_combine_stats" "draft_history"
 [4] "game"                "game_info"           "game_summary"
 [7] "inactive_players"    "line_score"          "officials"
[10] "other_stats"         "play_by_play"        "player"
[13] "team"                "team_details"        "team_history"
[16] "team_info_common"

#Introduction
**This is a markdown cell** (Double-Click this to edit)

This section should describe the background and objectives of the study

#Data Description
**This is a markdown cell**
(Double-Click this to edit)

This section should describe where the dataset comes from, the sample
size, how the data were collected, etc.

#Exploratory Data Analysis (EDA)

##1. Data Cleaning & Sample Selection

In [16]:
df_eda <- dbGetQuery(con, "
  SELECT
    g.game_id,
    g.game_date,
    g.season_id,

    -- Home Team Scoring (Response Variables)
    g.team_id_home AS home_team_id,
    g.pts_home AS home_pts,
    CASE WHEN g.pts_home > 100 THEN 1 ELSE 0 END AS high_scoring_100,

    -- Away Team Context (Covariates)
    g.team_id_away AS away_team_id,
    g.pts_away AS away_pts
  FROM game g
  WHERE g.pts_home IS NOT NULL
  LIMIT 5000
")
#5000 games only

head(df_eda)

  game_id    game_date           season_id home_team_id home_pts
1 0024600001 1946-11-01 00:00:00 21946     1610610035   66
2 0024600003 1946-11-02 00:00:00 21946     1610610034   56
3 0024600002 1946-11-02 00:00:00 21946     1610610032   59
4 0024600004 1946-11-02 00:00:00 21946     1610610025   63
5 0024600005 1946-11-02 00:00:00 21946     1610610028   33
6 0024600006 1946-11-03 00:00:00 21946     1610610026   71
  high_scoring_100 away_team_id away_pts
1 0                1610612752   68
2 0                1610610031   51
3 0                1610612738   53
4 0                1610612752   47
5 0                1610610036   50
6 0                1610610035   60

## 2. Summary Statistics and Univariate Analysis

In [4]:
summary_stats <- df_eda %>%
  reframe(
    Variable = c("Home Points (home_pts)", "Away Points (away_pts)"),
    Mean     = c(mean(home_pts), mean(away_pts)),
    SD       = c(sd(home_pts), sd(away_pts)),
    Median   = c(median(home_pts), median(away_pts)),
    IQR      = c(IQR(home_pts), IQR(away_pts)),
    Min      = c(min(home_pts), min(away_pts)),
    Max      = c(max(home_pts), max(away_pts))
  )

  summary_stats

  # Note: Away Points here means opponent points

  Variable               Mean    SD       Median IQR Min Max
1 Home Points (home_pts) 92.0752 18.54957 91     27  18  173
2 Away Points (away_pts) 86.8502 17.72099 85     25  19  153

##3. Visualizing Response Variables (Justifying Model Choices)

## 4. Relationship Between Covariates & Outcomes (Bivariate Analysis)

# Models
 **This is a markdown cell** (Double-Click this to edit)

This section should include at least two statistical models for the same dataset, justifications of the choices of the models, model diagnostics, parameter estimates and their standard errors and p-values, and interpretation of the results.

- Poisson
- Logistic

# Conclusion and Discussion
**This is a markdown cell** (Double-Click this to edit)


This section should provide overall conclusions, any limitations in the datasets and analyses, and validity of the conclusions.